manifest:
  remotes:
    - name: zmkfirmware
      url: https://github.com
    - name: crystalplanet
      url: https://github.com
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-rgb-fx
      remote: crystalplanet
      revision: main
  self:
    path: config
